### ISSUE TITLE
Add webscrobbler as part of the app

### ISSUE THREAD

**Issue by theli-ua** [rbiggers/electron-pandora#5]
https://chrome.google.com/webstore/detail/web-scrobbler/hhinaapppaileiechjoiifaancjggfjm

Webscrobbler is a chrome extension that allows songs you listen on pandora to be submitted to scrobbler services (last.fm, listenbrainz, libre.fm)

**Comment by rbiggers** [comment]
I will take a look at this and see what it would take to implement. I don't have a timeline unfortunately as I am really busy right now. If you would like to develop this feature yourself you are more than welcome to create a pull request.

**Comment by rbiggers** [comment]
@theli-ua so it looks as if Electron does not support the Chrome Extension API. Please refer to this [post](https://github.com/electron/electron/issues/13123#issuecomment-399662730).

So until Electron supports the Chrome Extension API or Web Scrobbler conforms to the already existing Electron Extension API there really isn't much that I can do.
