### ISSUE TITLE
(Suggestion) Remember Window State

### ISSUE THREAD

**Issue by M1kep** [rbiggers/electron-pandora#6]
Hi there,

Submitting this issue to see if window state persistence is something that would be considered for this app. 

It can be setup rather painlessly using electron-window-state ( https://github.com/mawie81/electron-window-state )

**Comment by rbiggers** [comment]
Hi M1kep,

I can take a look at it hopefully sometime this week or if you want to develop this feature feel free to submit a pull request.

**Comment by rbiggers** [comment]
I have added window state management with version [v0.2.2](https://github.com/rbiggers/electron-pandora/releases/tag/v0.2.2)
